export enum CompanyRole {
  COMPANY_OWNER = "COMPANY_OWNER",
  COMPANY_ADMIN = "COMPANY_ADMIN",
  BRANCH_OWNER = "BRANCH_OWNER",
  BRANCH_ADMIN = "BRANCH_ADMIN",
  SELLER = "SELLER",
  STOCK_ADMIN = "STOCK_ADMIN",
  STOCK_DISPATCHER = "STOCK_DISPATCHER",
  DRIVER = "DRIVER",
}
